trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  npm_config_cache: "$(Pipeline.Workspace)/.npm"

steps:

- task: NodeTool@0
  inputs:
    versionSpec: "20.x"
  displayName: "Use Node.js"

- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: "Cache npm"

- script: npm run build
  displayName: "Install dependencies"

- task: PublishPipelineArtifact@1
  displayName: "Publish automation artifact"
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)
    artifact: playwright-automation
    publishLocation: pipeline